swagger: '2.0'
info:
  title: Restaurants API
  description: API for managing restaurants
  version: 1.0.0
host: localhost:8080
basePath: /restaurants
schemes:
  - http
  - https
paths:
  /:
    get:
      summary: Get a list of restaurants
      responses:
        '200':
          description: OK
    post:
      summary: Add a new restaurant
      responses:
        '201':
          description: Created
  /{id}:
    put:
      summary: Update a restaurant by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
    delete:
      summary: Delete a restaurant by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: No Content
